(setq avli-conf-dir (concat user-emacs-directory "rc"))
(add-to-list 'load-path avli-conf-dir)

(require 'avli-packages)
(require 'avli-basic)
(require 'avli-color-theme)
(require 'avli-key-bindings)
(require 'avli-completion)
(require 'avli-prog-mode)
(require 'avli-c++)
(require 'avli-python)
(require 'avli-text)
(require 'avli-latex)
(require 'avli-lisp)
(require 'avli-russian)

(provide 'init)
