(setq avli-conf-dir (concat user-emacs-directory "rc"))
(add-to-list 'load-path avli-conf-dir)

(require 'avli-packages)
(require 'avli-basic)
(require 'avli-color-theme)
(require 'avli-key-bindings)
(require 'avli-completion)
(require 'avli-prog-mode)
(require 'avli-c++)
(require 'avli-python)
(require 'avli-text)
(require 'avli-latex)
(require 'avli-elisp)
(require 'avli-js)
(require 'avli-clojure)
(require 'avli-erlang)
(require 'avli-magit)
(require 'avli-smartparens)
(require 'avli-shell)
(require 'avli-term)
(require 'avli-russian)

(provide 'init)
;;; init.el ends here
